[base]
appns = "cz.potato.YtDownloader"
build_directory_link = "build"

[zig]
executable = "zig"

[[sources]]
url = "https://github.com/ocornut/imgui/archive/refs/tags/v1.89.2.tar.gz"
out = "imgui"
strip = 1

[[sources]]
url = "https://github.com/glfw/glfw/archive/refs/tags/3.3.8.tar.gz"
out = "glfw"
strip = 1

[[sources]]
url = "https://github.com/nlohmann/json/releases/download/v3.11.2/json.tar.xz"
out = "cpp-json"
strip = 1
