name: ci
on:
  pull_request:
  push:
  workflow_call:

jobs:
  x86_64-linux-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.12.0-dev.878+7abf9b3a8
      - name: Compile
        run: zig build -Doptimize=ReleaseFast
      - uses: actions/upload-artifact@v3
        with:
          name: zig-out
          path: |
            zig-out
          if-no-files-found: error
